### ISSUE TITLE
/bin/bash^M: bad interpreter

### ISSUE THREAD

**Issue by demogorgi** [ralfdonald/TingScript#4]
I had to do
\>dos2unix linux.sh
before I could use the script.

**Comment by frog23** [comment]
It worked for me when I tried it today and the repository hasn't changed your issue report. I tested both calling `git clone https://github.com/ralfdonald/TingScript.git` and going on the github page for linux.sh, clicking "View Raw" and saving the file (here I needed to run `chmod +x linux.sh` first). In both cases I didn't get the bad interpreter error.

**Comment by ralfdonald** [comment]
@demogorgi Maybe its a bad interpreter, but there exist no ^M in the files
@frog23 thanks for trying out the issue

**Comment by demogorgi** [comment]
Thank you. I also tried again with the latest commit, but also with earlier ones and do not experience problems. I don't know what went wrong last time.
